# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6da20fa5e184034a17b05784f16b716cd7236e4747978bef55f99d29c6df70e9a672cb67e932e4ca5b83ad70ac9b621d52dbe508f5ec94246cfd940bc0f84a9

test:
  secret_key_base: 4e293b6441b188a528088438ef1ab8eb4f7fca30dffd18c6c891809b68142e54f14dcc4a61785d6eb0c1006827027ad5a4ee801c02791bf41dd3eeaff4835104

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4e293b6441b188a528088438ef1ab8eb4f7fca30dffd18c6c891809b68142e54f14dcc4a61785d6eb0c1006827027ad5a4ee801c02791bf41dd3eeaff4835104
